apiVersion: v1
kind: Namespace
metadata:
  name: management-ui 
  labels:
    role: management-ui 
---
apiVersion: v1
kind: Namespace
metadata:
  name: stars
  labels:
    role: stars 
---
kind: Namespace
apiVersion: v1
metadata:
  name: client
  labels:
    role: client